version: ‘3.9’

volumes:
  db-data:

services:
  django:
    container_name: api-django
    build: ./api-django
    volumes:
      - ./api-django:/code
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    tty: true

  db:
    container_name: db
    build: ./mysql
    volumes:
      - db-data:/var/lib/mysql
      - ./mysql/initdb:/docker-entrypoint-initdb
    ports:
      - 3306:3306
    env_file:
      - .env
    healthcheck:
      test: mysqladmin ping -h${MYSQL_HOST} -u${MYSQL_USER} -p${MYSQL_PASSWORD}
      interval: 1s
      timeout: 1s
      retries: 100
      start_period: 1s
